-- 코드를 입력하세요
SELECT U.TITLE,
U.BOARD_ID,
R.REPLY_ID,
R.WRITER_ID,
R.CONTENTS,
 TO_CHAR(R.CREATED_DATE, 'yyyy-MM-dd') as CREATED_DATE
FROM USED_GOODS_BOARD U
INNER JOIN USED_GOODS_REPLY R
ON U.BOARD_ID = R.BOARD_ID
WHERE TO_CHAR(U.CREATED_DATE, 'yyyyMM') = '202210'
ORDER BY R.CREATED_DATE, U.TITLE
;