-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', F.BOARD_ID,'/' ,F.FILE_ID, F.FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F
INNER JOIN USED_GOODS_BOARD B
ON F.BOARD_ID = B.BOARD_ID
AND B.VIEWS = (
   SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY F.FILE_ID DESC