-- 코드를 입력하세요
SELECT B.BOOK_ID,
A.AUTHOR_NAME,
TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') as PUBLISHED_DATE
FROM BOOK B
INNER JOIN AUTHOR A 
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE